// {
//   jobTitle: 'Full Stack Developer (EST)',
//   companyInfo: 'EllieMD is on a mission to revolutionize healthcare by empowering individuals with pharmaceutical-grade products and a network of dedicated brand partners. The company believes healthcare should be accessible, transparent, and built on trust.',
//   experienceLevel: 'mid-level',
//   requiredSkills: [
//     'Next.js',
//     'Node.js',
//     'React',
//     'TypeScript',
//     'Express',
//     'RESTful APIs',
//     'MongoDB',
//     'Git',
//     'Jest',
//     'Tailwind',
//     'CSS frameworks',
//     'version control (Git)',
//     'testing (Jest)',
//     'modern frontend design systems (Tailwind or CSS frameworks)'
//   ],
//   preferredSkills: [
//     'HIPAA',
//     'FDA',
//     'healthcare compliance',
//     'Distributed systems or microservices architecture',
//     'AWS services (Lambda, ECS, S3, CloudWatch, etc.)',
//     'Infrastructure tooling (Docker, containers, cloud hosting)',
//     'CI/CD pipelines',
//     'Observability & analytics: Sentry',
//     'PostHog',
//     'Background job systems (Agenda, cron-based workers)',
//     'Heroku',
//     'Netlify deployment environments',
//     'PNPM monorepos and code quality tooling (ESLint, Prettier)'
//   ],
//   keyResponsibilities: [
//     'work across our Next.js + Node.js + React platform to enhance and maintain our',
//     'enhance and maintain our full-stack platform built on Next.js, React, TypeScript, Node.js, and Express.',
//     'Develop, enhance, and maintain our full-stack platform',
//     'Build scalable APIs, backend services, and modular frontend components.',
//     'Integrate third-party services including payments, authentication, analytics, notifications, and more.',
//     'Write automated tests, help improve code quality, and follow best-in-class engineering practices.',
//     'Participate in code reviews and support continuous improvement across the engineering team.',
//     'Support light DevOps work, including deployments, logging, monitoring, and CI enhancements.',
//     'Contribute to the evolution of the platform toward more distributed, cloud-native systems',
//     'Get acclimated to the codebase and assist in lighter feature and maintenance work',
//     'Take on more complex and impactful engineering tasks',
//     'Contributing member to our team culture and technical advancement',
//     'enhance and maintain our API backend (Express/TypeScript)',
//     'enhance and maintain our Medical provider integrations',
//     'enhance and maintain our Website and marketing systems'
//   ],
//   industryTerms: [
//     'remote role',
//     'fast-growing engineering team',
//     'fast-moving, innovative environment',
//     'full-stack platform',
//     'E-commerce subscription engine',
//     'Customer, Partner, and Admin portals',
//     'Internal tools and scripting workflows',
//     'Medical provider integrations',
//     'digital experience',
//     'microservice and cloud migrations',
//     'microservices',
//     'cloud migrations',
//     'cloud-native systems',
//     'Distributed systems',
//     'modular frontend components',
//     'best-in-class engineering practices',
//     'continuous improvement',
//     'DevOps',
//     'deployments',
//     'logging',
//     'monitoring',
//     'CI enhancements',
//     'regulated industries',
//     'healthtech products',
//     'consumer-facing healthtech products'
//   ],
//   keywords: [
//     'Full Stack Developer',
//     'Full Stack Developer (EST)',
//     'USA (EST)',
//     'remote role',
//     'periodic travel',
//     'team collaboration',
//     'fast-growing engineering team',
//     'engineering team',
//     'Position Overview',
//     'Position',
//     'About you',
//     "We're looking for",
//     'mission',
//     'revolutionize healthcare',
//     'pharmaceutical-grade products',
//     'network of dedicated brand partners',
//     'healthcare should be accessible',
//     'transparent',
//     'built on trust',
//     'upholding our values',
//     'accountability',
//     'collaboration',
//     'excellence',
//     'care',
//     'integrity',
//     'empowerment',
//     'supported',
//     'valued',
//     'protected',
//     'bring this mission to life',
//     'take pride in delivering high-quality experiences',
//     'thrive in a fast-moving, innovative environment',
//     'enhance and maintain',
//     'scale',
//     'scalable features',
//     'engineering foundation',
//     'technical advancement',
//     'team culture',
//     'technical decisions',
//     'ship features quickly',
//     'high quality',
//     'take on more complex and impactful engineering tasks',
//     'code reviews',
//     'code quality',
//     'automated tests',
//     'improve code quality',
//     'light DevOps work',
//     'support continuous improvement',
//     'technical systems',
//     'technical direction',
//     'contract role',
//     '1099 contractor',
//     'Future Conversion',
//     'full-time W2',
//     'Equal Opportunity Statement',
//     'equal opportunity employer',
//     'diversity',
//     'inclusive environment',
//     'all backgrounds',
//     'identities'
//   ],
//   softSkills: [
//     'upholding our values of accountability',
//     'collaboration',
//     'excellence',
//     'take pride',
//     'thrives',
//     'fast-moving',
//     'innovative environment',
//     'fast-growing',
//     'talented and diverse team',
//     'high-quality',
//     'play a key role',
//     'strengthening',
//     'preparing',
//     'great opportunity',
//     'thrives',
//     'excited',
//     'builder',
//     'takes pride',
//     'clean, maintainable, high-quality code',
//     'autonomy',
//     'ownership',
//     'rapid iteration',
//     'norm',
//     'Passionate about improving',
//     'A team player',
//     'values collaboration',
//     'enjoys learning from others',
//     'Aligned with EllieMD’s core values',
//     'Accountability',
//     'Collaboration',
//     'Excellence',
//     'Integrity',
//     'Care',
//     'Strong verbal and written communication skills',
//     'clearly articulate technical decisions'
//   ],
//   certifications: []
// }