export const supplimentTechSkills = [
    'Agile Development',
    'Apache Kafka',
    'API Development',
    'AWS Lambda',
    'AWS S3',
    'Azure Kubernetes Service',
    'CI/CD',
    'Docker',
    'Elasticsearch',
    'Git',
    'Kubernetes',
    'Node.js',
    'Python',
    'React',
    'Redis',
    'SQL',
    'Terraform',
    'WebSocket Protocol',
    'AWS DynamoDB',
]

export const supplimentSoftSkills = [
    'Accountability',
    'Adaptability',
    'Analytical Thinking',
    'Assertiveness',
    'Communication',
    'Conflict Management',
    'Collaboration',
    'Critical Thinking',
    'Decision Making',
    'Empathy',
    'Feedback Reception',
    'Flexibility',
    'Goal Setting',
    'Innovation',
    'Leadership',
    'Negotiation',
    'Problem Solving',
    'Teamwork',
    'Time Management',
    'Written Communication',
]